### ISSUE TITLE
props

### ISSUE THREAD

**Issue by headwinds** [AlexanderWingard/reagent-transition-group#1]
Just starring your project doesn't say enough so I just wanted to say thanks for creating this example - I learned a lot from it and used it in this [sandbox](https://github.com/headwinds/reagent-reframe-material-ui) - awesome work!

**Comment by AlexanderWingard** [comment]
> Just starring your project doesn't say enough so I just wanted to say thanks for creating this example - I learned a lot from it and used it in this [sandbox](https://github.com/headwinds/reagent-reframe-material-ui) - awesome work!

Hey man! Thanks for taking the time to write. I guess the good solution still doesn't work. Not sure if you saw it but this example is a response to issues put on reagent: https://github.com/reagent-project/reagent/issues/311

Will have a look at your project, looks cool.
Cheers!

**Comment by headwinds** [comment]
@AlexanderWingard yes that's how I found your work! I really liked what you did and how you leveraged D3 so I went with your approach instead
